<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-19T23:45:04 ICT" name="Full Regression Suite" finished-at="2025-03-19T23:45:27 ICT" duration-ms="22040">
    <groups>
    </groups>
    <test started-at="2025-03-19T23:45:04 ICT" name="Positive Login Tests" finished-at="2025-03-19T23:45:11 ICT" duration-ms="6890">
      <class name="com.practicetestautomation.tests.login.PositiveLoginTests">
        <test-method signature="testLoginFunctionality()[pri:0, instance:com.practicetestautomation.tests.login.PositiveLoginTests@7722c3c3]" started-at="2025-03-19T23:45:05 ICT" name="testLoginFunctionality" finished-at="2025-03-19T23:45:11 ICT" duration-ms="6782" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.practicetestautomation.tests.login.PositiveLoginTests.testLoginFunctionality(PositiveLoginTests.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginFunctionality -->
      </class> <!-- com.practicetestautomation.tests.login.PositiveLoginTests -->
    </test> <!-- Positive Login Tests -->
    <test started-at="2025-03-19T23:45:11 ICT" name="Negative Login Tests" finished-at="2025-03-19T23:45:27 ICT" duration-ms="15108">
      <class name="com.practicetestautomation.tests.login.NegativeLoginTests">
        <test-method signature="incorrectPasswordTest()[pri:0, instance:com.practicetestautomation.tests.login.NegativeLoginTests@2d7275fc]" started-at="2025-03-19T23:45:11 ICT" name="incorrectPasswordTest" finished-at="2025-03-19T23:45:18 ICT" duration-ms="6414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectPasswordTest -->
        <test-method signature="incorrectUssernameTest()[pri:0, instance:com.practicetestautomation.tests.login.NegativeLoginTests@2d7275fc]" started-at="2025-03-19T23:45:18 ICT" name="incorrectUssernameTest" finished-at="2025-03-19T23:45:27 ICT" duration-ms="8688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectUssernameTest -->
      </class> <!-- com.practicetestautomation.tests.login.NegativeLoginTests -->
    </test> <!-- Negative Login Tests -->
  </suite> <!-- Full Regression Suite -->
</testng-results>
